### ISSUE TITLE
GPIO callbacks have time in seconds instead of microseconds.

### ISSUE THREAD

**Issue by prasha-au** [fikin/nodemcu-lua-mocks#11]
Just playing around with this so I'm not 100% across all the quirks. Please excuse me if I've missed something.

I believe there's a bug in the GPIO pin trigger mock in that it returns the incorrect unit of time.

`os.time()` is used [here](https://github.com/fikin/nodemcu-lua-mocks/blob/master/lua/gpio_pin_state.lua#L70). However, the [NodeMCU docs](https://nodemcu.readthedocs.io/en/release/modules/gpio/#parameters_3) state that the value is passed in microseconds and the [Lua docs](https://www.lua.org/pil/22.1.html) state that in most systems this is returned in seconds. I noticed this on a Docker Alpine image.

**Comment by fikin** [comment]
thanks for spotting it. fixed to tmr.now() source.
